URL = ".//{http://www.portalfiscal.inf.br/nfe}"
DEFAULT_FIELD_HEIGHT = 6
DEFAULT_HEIGHT_FONT_CONTENT = 3
HEIGHT_FONT_BLOCK_DESC = 3
BASE_FONT_SIZES = {
    "FONT_SIZE_DESC": 5,
    "H_FONT_DESC": 2.8,
    "FONT_SIZE_CONT": 7,
    "RECEIPT_FONT": 5,
    "PRODUCT_DESCRIPTION": 6,
    "FONT_DUPLICATES": 7,
}
